export const audios = {
  A: require("../audios/alfabeto/A.mp3"),
  B: require("../audios/alfabeto/B.mp3"),
  C: require("../audios/alfabeto/C.mp3"),
  D: require("../audios/alfabeto/D.mp3"),
  E: require("../audios/alfabeto/E.mp3"),
  F: require("../audios/alfabeto/F.mp3"),
  G: require("../audios/alfabeto/G.mp3"),
  H: require("../audios/alfabeto/H.mp3"),
  I: require("../audios/alfabeto/I.mp3"),
  J: require("../audios/alfabeto/J.mp3"),
  K: require("../audios/alfabeto/K.mp3"),
  L: require("../audios/alfabeto/L.mp3"),
  M: require("../audios/alfabeto/M.mp3"),
  N: require("../audios/alfabeto/N.mp3"),
  O: require("../audios/alfabeto/O.mp3"),
  P: require("../audios/alfabeto/P.mp3"),
  Q: require("../audios/alfabeto/Q.mp3"),
  R: require("../audios/alfabeto/R.mp3"),
  S: require("../audios/alfabeto/S.mp3"),
  T: require("../audios/alfabeto/T.mp3"),
  U: require("../audios/alfabeto/U.mp3"),
  V: require("../audios/alfabeto/V.mp3"),
  W: require("../audios/alfabeto/W.mp3"),
  X: require("../audios/alfabeto/X.mp3"),
  Y: require("../audios/alfabeto/Y.mp3"),
  Z: require("../audios/alfabeto/Z.mp3"),
};