export const audios = {
  A: require("@/components/audios/A.mp3"),
  B: require("@/components/audios/B.mp3"),
  C: require("@/components/audios/C.mp3"),
  D: require("@/components/audios/D.mp3"),
  E: require("@/components/audios/E.mp3"),
  F: require("@/components/audios/F.mp3"),
  G: require("@/components/audios/G.mp3"),
  H: require("@/components/audios/H.mp3"),
  I: require("@/components/audios/I.mp3"),
  J: require("@/components/audios/J.mp3"),
  K: require("@/components/audios/K.mp3"),
  L: require("@/components/audios/L.mp3"),
  M: require("@/components/audios/M.mp3"),
  N: require("@/components/audios/N.mp3"),
  O: require("@/components/audios/O.mp3"),
  P: require("@/components/audios/P.mp3"),
  Q: require("@/components/audios/Q.mp3"),
  R: require("@/components/audios/R.mp3"),
  S: require("@/components/audios/S.mp3"),
  T: require("@/components/audios/T.mp3"),
  U: require("@/components/audios/U.mp3"),
  V: require("@/components/audios/V.mp3"),
  W: require("@/components/audios/W.mp3"),
  X: require("@/components/audios/X.mp3"),
  Y: require("@/components/audios/Y.mp3"),
  Z: require("@/components/audios/Z.mp3"),
};