export const audios = {
  A: require("@componets/audios/A.mp3"),
  B: require("@componets/audios/B.mp3"),
  C: require("@componets/audios/C.mp3"),
  D: require("@componets/audios/D.mp3"),
  E: require("@componets/audios/E.mp3"),
  F: require("@componets/audios/F.mp3"),
  G: require("@componets/audios/G.mp3"),
  H: require("@componets/audios/H.mp3"),
  I: require("@componets/audios/I.mp3"),
  J: require("@componets/audios/J.mp3"),
  K: require("@componets/audios/K.mp3"),
  L: require("@componets/audios/L.mp3"),
  M: require("@componets/audios/M.mp3"),
  N: require("@componets/audios/N.mp3"),
  O: require("@componets/audios/O.mp3"),
  P: require("@componets/audios/P.mp3"),
  Q: require("@componets/audios/Q.mp3"),
  R: require("@componets/audios/R.mp3"),
  S: require("@componets/audios/S.mp3"),
  T: require("@componets/audios/T.mp3"),
  U: require("@componets/audios/U.mp3"),
  V: require("@componets/audios/V.mp3"),
  W: require("@componets/audios/W.mp3"),
  X: require("@componets/audios/X.mp3"),
  Y: require("@componets/audios/Y.mp3"),
  Z: require("@componets/audios/Z.mp3"),
};